[postgres]
url      = "127.0.0.1"
DBName   = "db"
Port     = 5432
UserName = "root"
Password = "pass"

[redis]
url      = "127.0.0.1"
Port     = 6379
Password = "pass"
DB       = 0

[minio]
Url = "127.0.0.1:9000"
AccessKeyID = "user"
SecretAccessKey = "pass"
BucketName = "superstar"
