// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SuperStar/handlers"
	"SuperStar/internal/config"
	"SuperStar/internal/repos"
	"SuperStar/internal/services"
	"SuperStar/routes"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig, err := config.NewCfg()
	if err != nil {
		return nil, nil, err
	}
	db := repos.NewDB(configConfig)
	dbData, cleanup, err := repos.NewDBData(db)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := repos.NewAccountRepo(dbData)
	transaction := repos.NewTransaction(dbData)
	accountService := services.NewAccountService(accountRepo, transaction)
	accountHandler := handlers.NewAccountHandler(accountService)
	app := routes.NewRoute(accountHandler)
	mainApp := NewApp(configConfig, app)
	return mainApp, func() {
		cleanup()
	}, nil
}
